import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Terms of Service — GetSignalHooks",
  alternates: {
    canonical: "https://www.getsignalhooks.com/terms",
  },
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[#0a0a0b] text-zinc-300">
      <div className="mx-auto max-w-3xl px-6 py-20">
        <Link
          href="/"
          className="text-sm text-zinc-500 hover:text-zinc-300 transition-colors"
        >
          &larr; Back to home
        </Link>

        <h1 className="mt-8 text-3xl font-bold text-white">Terms of Service</h1>
        <p className="mt-2 text-sm text-zinc-500">Last updated: 4 March 2025</p>

        <div className="mt-10 space-y-8 text-[0.9375rem] leading-[1.8]">
          <section>
            <h2 className="text-lg font-semibold text-white mb-3">1. Agreement</h2>
            <p>
              By accessing or using GetSignalHooks (&quot;the Service&quot;), you agree to be bound by
              these Terms. If you do not agree, do not use the Service.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">2. Description of Service</h2>
            <p>
              GetSignalHooks provides AI-powered sales hook generation, follow-up email automation,
              and lead management tools via a web application and API.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">3. Accounts</h2>
            <ul className="list-disc pl-6 space-y-1">
              <li>You must provide accurate information when creating an account.</li>
              <li>You are responsible for maintaining the security of your account credentials.</li>
              <li>You must be at least 18 years old to use the Service.</li>
              <li>One person or organisation per account; sharing login credentials is not permitted.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">4. Subscriptions and billing</h2>
            <ul className="list-disc pl-6 space-y-1">
              <li>Paid plans are billed monthly via Stripe. All prices are in GBP.</li>
              <li>The Free plan requires no payment. The Pro plan is billed monthly at $79/mo.</li>
              <li>You may cancel at any time through the billing portal. Access continues until the end of the current billing period.</li>
              <li>Refunds are not provided for partial billing periods, except as required by law.</li>
              <li>We reserve the right to change pricing with 30 days&apos; notice to existing subscribers.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">5. Usage limits</h2>
            <p>
              Each plan has a monthly hook generation limit. Unused hooks do not roll over.
              Limits reset on your billing anniversary date. We may throttle or suspend access
              if you exceed your plan limits or engage in abusive usage.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">6. Acceptable use</h2>
            <p className="mb-3">You agree not to:</p>
            <ul className="list-disc pl-6 space-y-1">
              <li>Use the Service to send spam or unsolicited bulk email</li>
              <li>Violate any applicable anti-spam laws (CAN-SPAM, GDPR, PECR, etc.)</li>
              <li>Upload false, misleading, or harmful content</li>
              <li>Attempt to reverse-engineer, scrape, or abuse the Service</li>
              <li>Share API keys or account access with unauthorised parties</li>
              <li>Use the Service for any illegal purpose</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">7. AI-generated content</h2>
            <p>
              Hooks and emails generated by the Service are AI-produced suggestions. You are
              responsible for reviewing and editing all content before sending. We do not guarantee
              the accuracy, completeness, or appropriateness of generated content.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">8. Intellectual property</h2>
            <p>
              You retain ownership of your data (leads, uploaded content). We retain ownership
              of the Service, its code, design, and branding. AI-generated hooks and emails are
              licensed to you for your commercial use.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">9. Limitation of liability</h2>
            <p>
              To the maximum extent permitted by law, GetSignalHooks shall not be liable for any
              indirect, incidental, special, consequential, or punitive damages, including loss of
              revenue, data, or business opportunities, arising from your use of the Service.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">10. Service availability</h2>
            <p>
              We aim for high availability but do not guarantee uninterrupted service. We may
              perform maintenance, updates, or modifications that temporarily affect access.
              We will provide reasonable notice for planned downtime.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">11. Termination</h2>
            <p>
              We may suspend or terminate your account if you violate these terms. You may
              close your account at any time by contacting us. Upon termination, your data
              will be handled in accordance with our{" "}
              <Link href="/privacy" className="text-emerald-400 hover:underline">
                Privacy Policy
              </Link>.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">12. Changes to these terms</h2>
            <p>
              We may update these terms from time to time. Continued use of the Service after
              changes constitutes acceptance. We will notify registered users of material changes
              via email.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">13. Governing law</h2>
            <p>
              These terms are governed by the laws of England and Wales.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">14. Contact</h2>
            <p>
              Questions about these terms? Email us at{" "}
              <a href="mailto:hello@getsignalhooks.com" className="text-emerald-400 hover:underline">
                hello@getsignalhooks.com
              </a>.
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
